import { v4 as uuidv4 } from 'uuid';

drop table if exists chest;
drop table if exists player;
drop table if exists users;
drop table if exists chest_type;
drop table if exists clan;

create table clan (
  id bigint generated by default as identity primary key,
  name text
);

create table chest_type (
  id bigint generated by default as identity primary key,
  source text
);

create table users (
  id uuid not null primary key,
  email text,
  clan_id bigint references clan on delete cascade not null
);

create table player (
  id bigint generated by default as identity primary key,
  name text not null,
  clan_id bigint references clan on delete cascade not null,
  done boolean default true,
  might int
);

create table chest (
  id bigint generated by default as identity primary key,
  title text,
  source text,
  level int,
  player_id bigint references player on delete cascade not null,
  chest_type_id bigint references chest_type on delete cascade not null,
  uploaded_by uuid references public.users not null default auth.uid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- Function for handling new users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, clan_id)
  values (new.id, new.email, new.clan_id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


INSERT INTO chest_type (source)
VALUES
    ('Bank'),
    ('Arena'),
    ('Crypt'),
    ('epic Crypt'),
    ('rare Crypt'),
    ('Citadel'),
    ('Clan wealth'),
    ('Rush tournament'),
    ('Epic inferno squad'),
    ('Epic Undead squad'),
    ('Heroic monster'),
    ('Mercenary Exchange'),
    ('Union of Triumph personal reward'),
    ('Rise of the Ancients event');

INSERT INTO clan (name)
VALUES
    ('VOV');

INSERT INTO player (name, clan_id)
VALUES
    ('Lady T', 1);
    ('Mordriel', 1);
    ('Old Dog', 1);
    ('Superretard77', 1);
    ('StrmRaiser', 1);
    ('Falete', 1);
    ('Reverso', 1);
    ('Bikerdad', 1);
    ('Athena', 1);
    ('Mamba Out', 1);
    ('Giperion', 1);
    ('VaLeRa', 1);
    ('JK Sublime', 1);
    ('Shahuginn', 1);
    ('KadeT', 1);
    ('EL DRAGON', 1);
    ('ALTER EGO', 1);
    ('Murat', 1);
    ('Tran Quoc Tuan', 1);
    ('Mohammad khater', 1);
    ('Da nu na kh', 1);
    ('Shlik', 1);
    ('GokTurk', 1);
    ('Hitsu', 1);
    ('Shiv', 1);
    ('Dark Pharoah', 1);
    ('Christian', 1);
    ('Landis', 1);
    ('Waldo', 1);
    ('Dev', 1);
    ('Anaragar', 1);
    ('quiker', 1);
    ('Tanich', 1);
    ('Achilles Duong', 1);
    ('Dariing', 1);
    ('LADISLAV', 1);
    ('Kelerne', 1);
    ('Rail', 1);
    ('Kristina Dorokhina', 1);
    ('Archon', 1);
    ('ARAGORN', 1);
    ('amiral dz', 1);
    ('ZEUS', 1);
    ('aziz bey', 1);
    ('Landaswyn', 1);
    ('odysseu', 1);
    ('Mehmet', 1);
    ('Leonidas', 1);
    ('Aarezher', 1);
    ('ExclusivE', 1);
    ('Kylian The Slayer', 1);
    ('Ghost', 1);
    ('prince of persia', 1);
    ('Storm', 1);
    ('LANDLORD', 1);
    ('Tarik', 1);
    ('Mr Nimbus', 1);
    ('llValkiriall', 1);
    ('SHIVA', 1);
    ('Lancelot', 1);
    ('GOR', 1);
    ('Shatis', 1);
    ('Malobandis', 1);
    ('Begon', 1);
    ('Roronoa Zoro', 1);
    ('Romanych', 1);
    ('Speeno', 1);
    ('Volksie', 1);
    ('Moriel', 1);
    ('Peter', 1);
    ('throne de fer', 1);
    ('OLMEZ', 1);
    ('Fox Kaisa', 1);
    ('Ilkilir', 1);
    ('Beameena', 1);
    ('Slaven79', 1);
    ('Kaos', 1);
    ('Zolosho', 1);
    ('Evgeniya', 1);
    ('White Reaper', 1);
    ('Roli', 1);
    ('Nidaen', 1);
    ('DEFKALION', 1);
    ('Kloyn AdA', 1);
    ('Aegrosad', 1);
    ('Turgon', 1);
    ('Mr D', 1);
    ('Roma', 1);
    ('Shivaji', 1);
    ('Hyperion', 1);
    ('ZOVIS', 1);
    ('Cordobe', 1);
    ('Daledor', 1);
    ('Beanara', 1);
    ('Sir JK', 1);
    ('Zites', 1);
    ('Shajas', 1);
    ('Mordriel jr', 1);
    ('OD Conquest', 1);